"""add dasn_simei_config, cancelado status, replace unique constraint with index

Revision ID: 7618d98adc77
Revises: 0df3edca7001
Create Date: 2026-08-30 10:07:35.925049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7618d98adc77'
down_revision: Union[str, Sequence[str], None] = '0df3edca7001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dasn_simei_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dias_antecedencia_lembrete', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite nao suporta ALTER de constraints diretamente - precisa de batch
    # mode (recria a tabela por baixo dos panos com a constraint jah removida).
    with op.batch_alter_table('obligation_instances', schema=None) as batch_op:
        batch_op.drop_constraint('uq_obligation_user_tipo_competencia', type_='unique')
        batch_op.create_index('ix_obligation_user_tipo_competencia', ['user_id', 'tipo', 'competencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obligation_instances', schema=None) as batch_op:
        batch_op.drop_index('ix_obligation_user_tipo_competencia')
        batch_op.create_unique_constraint('uq_obligation_user_tipo_competencia', ['user_id', 'tipo', 'competencia'])
    op.drop_table('dasn_simei_config')
    # ### end Alembic commands ###
