"""add nf_config table

Revision ID: f88d0d4be172
Revises: 620046d6ca98
Create Date: 2026-08-29 22:38:03.092395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88d0d4be172'
down_revision: Union[str, Sequence[str], None] = '620046d6ca98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nf_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tomador_razao_social', sa.String(length=255), nullable=True),
    sa.Column('tomador_cnpj', sa.String(length=32), nullable=True),
    sa.Column('tomador_email', sa.String(length=255), nullable=True),
    sa.Column('descricao_servico', sa.Text(), nullable=True),
    sa.Column('valor_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dia_emissao', sa.Integer(), nullable=False),
    sa.Column('dias_antecedencia_lembrete', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nf_config')
    # ### end Alembic commands ###
